6 Comments done
VeronikaD14/project2 pull request #3
Opened 2023-06-01 11:21 UTC by VeronikaD14

2023-06-01 13:58 UTC, MrMcSnail requested changes
Your utils module is currently a saved as a .jsx file. It's not returning a functional component and doesn't use .jsx so it's not an appropriate file extension and should not be in the components directory. 

I'd suggest that you have a .js file which contains your api calls called `api.js` and save that in a directory called `utils` in the `src` directory. 
`./src/utils/api.js`

2023-06-01 13:58 UTC, MrMcSnail commented on src/components/RevievCard.jsx
> +
You might want to destructure revCard here in order to tidy up your render statement below.

2023-06-01 13:58 UTC, MrMcSnail commented on src/components/RevievCard.jsx
> +    {revCard && <h2>Title: {revCard.title}</h2>}
No need for the conditional logic based on revCard being truthy here. Your loading state is bound to the revCard state and revCard will always have a truthy value if isLoading is false. So I'd get rid of the logical AND operators here.

2023-06-01 13:58 UTC, MrMcSnail commented on src/components/RevievCard.jsx
> +    {showComments &&<Comments comments={comments}/>}
Keep things consistent and use a ternary operator here. It can resolve to a jsx snippet `<></>` if showComments is falsy.

2023-06-01 13:58 UTC, MrMcSnail commented on src/components/RevievCard.jsx
> +            console.log(review)
Cheeky console.log!

2023-06-01 13:58 UTC, MrMcSnail commented on src/components/RevievCard.jsx
> +        <>
No need for the snippet here as the whole expression which starts on line 39 is a child of <section>

2023-06-01 13:58 UTC, MrMcSnail commented on src/components/RevievCard.jsx
> +    {showComments &&<Comments comments={comments}/>}
You comments should be part of a new section

2023-06-02 09:38 UTC, leekli requested changes
Hi Veronika, well done on this ticket so far.

Thank you for making the requested changes which Kyle asked for.

I have 2 additional bits of feedback:
* Review number 14 has no comments associated with that review, I am able to expand the 'Show comments' box but nothing shows, it might be worth putting some HTML here to tell the user there are no comments 
* Your app isn't entirely responsive to a mobile view, the images seem to go across the page quite alot and means I have to scroll right to see it all. The image should automatically resize to the size of the screen so it all fits on the screen, without the need to scroll. I will send you a Slack DM along with a short video which will show you what I see. I'd also encourage you view the video I put on slack yesterday about building 'mobile first' along with some tips on how to do it, link here: [https://northcoders.slack.com/archives/C04V9V1FSSV/p1685626253044119](url)

Please review the above feedback, implement the changes, and then resubmit the PR for review. Well done so far!

2023-06-02 10:05 UTC, leekli approved these changes
Brilliant work Veronika - I can see you've made both changes requested, and it looks much better in mobile view - well done!

You are free to merge this branch

2023-06-02 10:17 UTC, merged